package com.ojcoleman.europa.configurable;

/**
 * Base class for all exceptions generated by classes in this package. This is mainly to allow detecting, in a catch
 * clause, if the exception being caught was generated by one of our classes.
 * 
 * @author O. J. Coleman
 */
public class ConfigurableException extends RuntimeException {
	public ConfigurableException(String message) {
		super(message);
	}

	public ConfigurableException(String message, Throwable cause) {
		super(message, cause);
	}
}
